#!/bin/bash

# SketchyBar config entrypoint. See: https://felixkratz.github.io/SketchyBar/config

PLUGIN_DIR="$CONFIG_DIR/plugins"

##### Bar Appearance #####
sketchybar --bar \
  height=32 \
  blur_radius=30 \
  position=top \
  padding_left=10 \
  padding_right=10 \
  color=0xd91e1e2e \
  border_width=0 \
  y_offset=0

##### Global defaults #####
sketchybar --default \
  updates=when_shown \
  icon.font="SF Pro:Bold:14.0" \
  icon.color=0xffcdd6f4 \
  label.font="SF Pro:Semibold:13.0" \
  label.color=0xffcdd6f4 \
  padding_left=5 \
  padding_right=5 \
  label.padding_left=4 \
  label.padding_right=4 \
  icon.padding_left=4 \
  icon.padding_right=4

##### Workspaces (AeroSpace) #####
for sid in $(aerospace list-workspaces --all); do
  sketchybar --add item space.$sid left \
    --set space.$sid \
    background.color=0xff313244 \
    background.corner_radius=5 \
    background.height=24 \
    background.drawing=off \
    label="$sid" \
    click_script="aerospace workspace $sid" \
    script="$PLUGIN_DIR/aerospace.sh $sid"
done

sketchybar --add event aerospace_workspace_change
sketchybar --add item space_separator left \
  --set space_separator icon= label.drawing=off padding_left=10 padding_right=10

##### Right side: clock, battery, volume #####
sketchybar --add item clock right \
  --set clock update_freq=10 icon=  script="$PLUGIN_DIR/clock.sh" \
  --subscribe clock system_woke

sketchybar --add item battery right \
  --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
  --subscribe battery power_source_change

sketchybar --add item volume right \
  --set volume script="$PLUGIN_DIR/volume.sh" \
  --subscribe volume volume_change

sketchybar --update
